name: Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_ACCOUNT: 470576235824
  AWS_REGION : us-west-2

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  Deploy-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.12'
        name: install kubectl
      - name: setup kubectl config
        run: |
          mkdir ${HOME}/.kube
          echo "$CLIENT_CONFIG" >> ${HOME}/.kube/config
        shell: bash
        env:
          CLIENT_CONFIG : ${{secrets.kube_config}}
      - name: confirm kubectl config
        run: |
          kubectl version
      - name: apply resources folder
        run: |
          kubectl apply -f k8s-resources
  Deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubActions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 22
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
          aws --version
      - name: Install CDK
        run: |
          npm install -g aws-cdk
          cdk --version
#      - name: Bootstrap CDK
#        run: |
#          cdk bootstrap aws://${{ env.AWS_ACCOUNT }}/${{ env.AWS_REGION }}
      - uses: actions/setup-go@v5
        name: Install Go
        with:
          go-version: '^1.22'
      - run: go version
      - name: Test
        run: |
          go test
      - name: Deploy
        run: |
          cdk destroy
