name: pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        name: Install Go
        with:
          go-version: '^1.22'
      - run: go version